-- Migration: επέκταση arrivals table για ταξίδι + PDA
ALTER TABLE arrivals
    ADD COLUMN IF NOT EXISTS departure_date DATETIME NULL AFTER arrival_time,
    ADD COLUMN IF NOT EXISTS port VARCHAR(100) NULL AFTER cargo_type,
    ADD COLUMN IF NOT EXISTS port_charges DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS pilotage DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS towage DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS berth_dues DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS services DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS garbage DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS crew_changes DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS cargo_ops DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS customs_docs DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS agency_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00;
